SCREEN_WIDTH = 768
SCREEN_HEIGHT = 432

HORIZONTAL_BLOCKS = 16
VERTICAL_BLOCKS = 9

BLOCKS_WIDTH = SCREEN_WIDTH / HORIZONTAL_BLOCKS
BLOCKS_HEIGHT = SCREEN_HEIGHT / VERTICAL_BLOCKS

PLAYER_SPEED = 3.5
GRAVITY = 6.8